### ISSUE TITLE
재홍님 안녕하세요 피드백 전달 드립니다 ~:)

### ISSUE THREAD

**Issue by hcson9** [mocha-rm/scheduler#1]
# 좋은점
- SQL 문을 정말 잘 사용하시는 것 같습니다
    - ``를 사용하셔서 예약어도 방어할 수 있겠네요 
- Page 객체까지 사용해서 페이징 처리를 정말 잘해주신 것 같습니다
- `@ExceptionHandler` 를 사용하여 저희가 요구했던 내용을 잘 충족해주신 것 같습니다.
# 아쉬운점
- 아래와 같은 주석은 차라리 javadoc 형식으로 작성해주신 걸 추천드립니다. -> 참고로 자바에선 Javadoc 이면 충분합니다
```java
    /*
     * 전체 일정 조회
     * Default 조회 (조건 없이) http://localhost:8080/schedules?page=0
     * 작성자와 날짜로 조회 http://localhost:8080/schedules?authorId=1&modDate=2024-11-07&page=0
     * 작성자로 조회 http://localhost:8080/schedules?authorId=1&page=2
     * 날짜로 조회 http://localhost:8080/schedules?modDate=2024-11-06&page=1
     * */
```
- 위와 같은 상황엔 개인적으로는  `@RequiredArgsConstructor` 이 좀 더 좋아보입니다. -> 동일하게 ErrorCode Enum 도 같은생각입니다.
    - `@AllArgsConstructor` 를 상황에 맞게 쓰면 좋을것 같습니다
    -  [롬복 @All/NoArgsConstructor 제대로 알고 사용해보자.](https://velog.io/@code-10/%EB%A1%AC%EB%B3%B5-AllNoArgsConstructor-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EC%95%8C%EA%B3%A0-%EC%82%AC%EC%9A%A9%ED%95%B4%EB%B3%B4%EC%9E%90)
    - [@AllArgsConstructor를 지양해야 하는 이유](https://techjisu.tistory.com/155#)
```java
@Getter
@AllArgsConstructor
public class CustomException extends Exception {
    private final ErrorCode errorCode;
}
```
- query builder 생성 부분에서 조금 수정되면 좋을 것 같은 부분으로 예시 전달 드립니다.
    - 확인해보니 밑에 중복코드가 또 있네요. 하나의 메소드로 리팩토링 해보시는 걸 추천드립니다.
```java
    @Override
    public List<ScheduleResponseDto> findSchedules(Optional<Long> authorId, Optional<LocalDate> modDate, Pageable pageable) {
        StringBuilder sql = new StringBuilder("SELECT * FROM SCHEDULES WHERE 1=1");
        List<Object> params = new ArrayList<>();

        // 조건에 따라 SQL 쿼리 생성
        if (authorId.isPresent()) {
            sql.append(" AND USER_ID = ?");
            params.add(authorId.get());
        }
        if (modDate.isPresent()) {
            sql.append(" AND DATE(MOD_DATE) = ?");
            params.add(modDate.get());
        }
        sql.append(" ORDER BY MOD_DATE DESC LIMIT ? OFFSET ?");
        params.add(pageable.getPageSize());
        params.add(pageable.getOffset());

        return jdbcTemplate.query(sql.toString(), schedulesRowMapper(), params.toArray());
    }

```
# 추가사항
- 404 Error 코드에 대해서 고민해보신적이 있으실까요? 아래 글이 있어 한번 확인해보셔도 좋을 것 같아요
    - [데이터가 없을 때 200인가 404인가?](https://techblog.yogiyo.co.kr/%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B0%80-%EC%97%86%EC%9D%84-%EB%95%8C-200%EC%9D%B8%EA%B0%80-404%EC%9D%B8%EA%B0%80-f1c8c39ca9df) 
- Impl 을 구현하는 이유에 대해서 고려해보신 적이 있을까요?!
    - 잘못된 점은 아니나 한번쯤은 고민해보신느 것도 좋을 것 같아 공유드립니다. 
    - [ServiceImpl 쓰지말까?](https://stonehee99.tistory.com/37)

**Comment by mocha-rm** [comment]
피드백 감사합니다 !
